
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 17 20:50:38 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSE_BRACKET = 16;
  public static final int AND = 21;
  public static final int ELSE = 20;
  public static final int LESS_EQUAL = 26;
  public static final int OR = 22;
  public static final int EQUAL = 24;
  public static final int SEMI = 17;
  public static final int CHAR = 8;
  public static final int WHILE = 14;
  public static final int END = 4;
  public static final int GREATER_EQUAL = 28;
  public static final int GREATER = 27;
  public static final int COLON = 11;
  public static final int ID = 5;
  public static final int PROGRAM = 2;
  public static final int OPEN_BRACKET = 15;
  public static final int BEGIN = 3;
  public static final int BOOLEAN = 13;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int UNEQUAL = 25;
  public static final int EPSILON = 6;
  public static final int CONST = 19;
  public static final int error = 1;
  public static final int DOT = 9;
  public static final int ASSIGN = 10;
  public static final int INTEGER = 7;
  public static final int REAL = 12;
  public static final int LESS = 23;
}

